### ISSUE TITLE
窗口设置问题和链接问题

### ISSUE THREAD

**Issue by ishland** [iirose-tools/electron-iirose#1]
设置中的窗口设置有问题：
![image](https://user-images.githubusercontent.com/30385023/54865574-5ce40980-4da2-11e9-8753-4526b9db755b.png)
链接问题：
vid: 
https://f.iirose.com/file/67/1553340055_5c96169780e8d.mp4

**Comment by TheresaQWQ** [comment]
链接问题已修复，窗口问题是Electron的问题，暂时无法修复

**Comment by ishland** [comment]
我认为应该是缩放的问题，让用户设置一个缩放值然后正确计算就好了

**Comment by TheresaQWQ** [comment]
> 我认为应该是缩放的问题，让用户设置一个缩放值然后正确计算就好了

好的，我会尝试修复
