### ISSUE TITLE
JavaScript error when not connected to the internet

### ISSUE THREAD

**Issue by probonopd** [iirose-tools/electron-iirose#3]
JavaScript error when not connected to the internet:

![](https://github.com/AppImage/appimage.github.io/blob/dba18aba8293ff2b55ddfb6485061fa9905810b4/database/IIROSE/screenshot.png?raw=true)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1414

**Comment by ishland** [comment]
All right.
This issue will be fixed in the next release.

**Comment by probonopd** [comment]
Please ping me once the next release is out so that I can run the test again. Thanks!
